### ISSUE TITLE
Installation instructions (Linux)

### ISSUE THREAD

**Issue by mattrei** [josephwilk/shaderview#1]
Hi Joseph,

I tried to get shaderview running on my Ubuntu 14.04 machine. It was not easy though.
Here are the caveats I ran into (mostly its because of errors in the oF addons):
- ofxEditor: would not compile because in the src/ClipBoard.cpp the ClipBoard.h is spelled wrongly. Did a pull request already there. for now we have to fix it manually.
- ofxOsc: dont use the addon which ships with oF 8.0.x; use that one which is suggested in the README.md of shaderview
- ofxPostProcessing: the current master is not working with the latest oF 8.0.4: in src/PostProcessing.h in line 52 and 53 remove the 'const' so it machte oF function signatures
- ofxFft: you need this library 'sudo apt-get install libfftw3-dev '; and then in shaderviews 'config.make' add 'USER_LDFLAGS = -lfftw3f'

**Comment by josephwilk** [comment]
Great work, thanks! I'll add that to the Readme.

So did you succeed it getting it running on unbuntu?

**Comment by mattrei** [comment]
Cool. Yes it runs :)! Seeing some lights in the tunnel...

**Comment by josephwilk** [comment]
This is now in the README. Thanks!
